server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets: [localhost]
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: renote_monolithic_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: renote_monolithic_logs
          __path__: /mnt/logs/renote/*.log
      - targets: [localhost]
        labels:
          job: renote_monolithic_logs
          __path__: /mnt/logs/renote/*.txt

  - job_name: genai_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: genai_logs
          __path__: /mnt/logs/genai/*.log
      - targets: [localhost]
        labels:
          job: genai_logs
          __path__: /mnt/logs/genai/*.txt
